import { ReduxProvider } from '../redux/provider';
import './globals.css';
import { Inter } from 'next/font/google';
import { Roboto } from 'next/font/google';
const inter = Inter({ subsets: ['latin'] });

const roboto = Roboto({
	subsets: ['latin'],
	weight: ['500', '700'],
});

export const metadata = {
	title: 'Food App',
	description: 'Generated by Henry Team#14',
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<ReduxProvider>
				<body className={roboto.className}>{children}</body>
			</ReduxProvider>
		</html>
	);
}
